trigger:
  branches:
    include:
      - main

pool: Default

parameters:
  - name: runScan
    displayName: "Run Scanning Stage?"
    type: boolean
    default: true
    values:
      - true
      - false

variables: 
  WorkDir: '$(System.DefaultWorkingDirectory)/Environment/dev'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: TerraformInitAndPlan
        displayName: Terraform Init And Plan
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(WorkDir)
            backendServiceArm: 'ServiceConnection12'
            backendAzureRmStorageAccountName: 'tfstate1230'
            backendAzureRmContainerName: 'tfcontainer'
            backendAzureRmKey: 'demo.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(WorkDir)
            environmentServiceNameAzureRM: 'ServiceConnection12'

  - stage: Scan
    displayName: Scanning Stage
    jobs:
      - job: TFSec
        displayName: TFSec Scan
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'

  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - job: ManualValidation
        displayName: Manual Validation
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'priya@jaiswal4656outlook.onmicrosoft.com'
            approvers: 'priya@jaiswal4656outlook.onmicrosoft.com'

      - job: TerraformApply
        displayName: Terraform Apply
        dependsOn: ManualValidation
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(WorkDir)
            backendServiceArm: 'ServiceConnection12'
            backendAzureRmStorageAccountName: 'tfstate1230'
            backendAzureRmContainerName: 'tfcontainer'
            backendAzureRmKey: 'demo.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: $(WorkDir)
            environmentServiceNameAzureRM: 'ServiceConnection12'
