trigger:
- main

jobs:
  - job: TerraformInitPlan
    displayName: Terraform Init Plan
    pool: Default
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
        backendServiceArm: 'ServiceConnection12'
        backendAzureRmStorageAccountName: 'tfstate1230'
        backendAzureRmContainerName: 'tfcontainer'
        backendAzureRmKey: 'demo.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
        environmentServiceNameAzureRM: 'ServiceConnection12'